services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      # KRaft instead of ZooKeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Connection configuration
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Auto-create topics (for development purposes)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Required for KRaft
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  postgres:
    image: postgres:15
    container_name: postgres-sql
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432" # can change the PORT in .env file
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./dashboard/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  producer:
    build: .
    container_name: producer
    command: python scripts/producer/api_listener.py
    depends_on:
      - kafka
    restart: always

  consumer:
    build: .
    container_name: consumer
    command: spark-submit --driver-memory 2G --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.7.3 scripts/consumer/spark_consumer.py
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    restart: on-failure
    
volumes:
  pgdata: